# Generated by Django 5.0.1 on 2024-02-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='downloadhistory',
            table='download_history',
        ),
        migrations.AlterModelTable(
            name='files',
            table='files',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
