# Generated by Django 5.0.1 on 2024-02-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_downloadhistory_table_alter_files_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownloadHistory',
            new_name='Download_History',
        ),
    ]
