# Generated by Django 5.0.1 on 2024-02-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='special_token',
        ),
    ]
