# Generated by Django 5.0.1 on 2024-02-03 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_special_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_link',
            fields=[
                ('download_link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.files')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'download_link',
            },
        ),
    ]
