# Generated by Django 5.0.1 on 2024-02-03 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_download_link_file_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_download_history',
            old_name='download_status',
            new_name='file_downloaded',
        ),
        migrations.AddField(
            model_name='files',
            name='file_type',
            field=models.CharField(choices=[('pptx', 'Powerpoint file'), ('docx', 'Document/Word file'), ('xlsx', 'Excel file')], default='docx', max_length=50),
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
